Implement first test for artist bounded context
atmosphere-pp/server pull request #7
Opened 2020-12-27 15:34 UTC by MagicalLas

바운디드 컨텍스트의 한가지인 artist라는 컨텍스트의 Application Service의 테스트를 작성하였습니다. 추후에는 Application Service의 메서드의 테스트를 점점 더 구현해나갈 예정입니다.
Application Service의 메서드들은 하나하나 UseCase가 되어야합니다. 또한, Application Service의 인터페이스만 보면 어떤 어플리케이션인지 알 수 있어야합니다. (클린아키텍처에서의 "소리치는 아키텍처")

2020-12-28 14:01 UTC, wickedev requested changes
흠 잡을게 없네요. 머지합니다.

2020-12-28 14:02 UTC, wickedev approved these changes

2020-12-28 14:02 UTC, merged

2020-12-29 07:14 UTC, MagicalLas commented on artist/src/test/kotlin/ArtistApplicationService.kt
> +                val artistId = applicationService.searchByName("michael jackson")
ArtistId라는 타입은 도메인 레이어에 있는 것이기에 사실 여기로 나오면 안될 것 같은데 나와버렸네요.

헥사고날 아키텍처(aka port and adapter)의 경우에는 application layer의 경계로 시스템의 내부와 외부가 결정되기 때문에 그 사이를 DTO와 같은걸로 분리하는게 좋긴 합니다. 다른 견해로 마틴파울러의 PoEAA에서는 DTO를 만드는게 불필요하다고 말하기도 합니다. 그러나 여기서도 도메인 객체들이 application layer의 외부로 나가면 안된다고 이야기합니다. 따라서 추후에 리턴 타입이 ArtistId가 아니도록 리팩터링 해야합니다.

@wickedev

2020-12-29 07:14 UTC, MagicalLas commented on artist/src/test/kotlin/ArtistApplicationService.kt
> +                val artistId = applicationService.searchByName("michael jackson")
혼자서 셀프 리뷰를 했다고 생각했지만 리뷰를 잘 못해서 이런 실수가 생겼네요ㅠㅠㅠㅠ